name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: scuba13/amacoon_nginx:latest

    # - name: Trigger Deploy to AWS Lightsail
    #   uses: peter-evans/repository-dispatch@v1
    #   with:
    #     token: ${{ secrets.REPO_ACCESS_TOKEN }}
    #     repository: scuba13/AmacoonDocker
    #     event-type: new_docker_image
