name: Docker Build and Push

on:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Build Docker image
      run: docker build -t amacoon-nginx .
  
    - name: Push Docker image to Lightsail
      run: |
        aws lightsail push-container-image --service-name amacoon \
        --label amacoon-nginx \
        --image amacoon-nginx

    - name: Trigger Deploy to AWS Lightsail
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: scuba13/AmacoonDocker
        event-type: new_docker_image
